/**
 * Memory Layer types (ADR-0005).
 *
 * The MemoryRef shape is the in-flight memory state consumed by LoopContext.
 * The MemoryStore interface is the persistence abstraction (Mock / D1 / KV).
 *
 * NOTE: This file is the canonical home for MemoryRef/MemoryStore types per
 * ADR-0005. Do NOT add these to web/src/lib/types.ts (shared types).
 */

/** MemoryRef.type — categorizes the memory entry. */
export type MemoryRefType =
  | "conversation"
  | "user_profile"
  | "agent_trace"
  | "agent_step"
  | "citation"
  | string; // forward-compat for Phase 1.5 Vectorize refs

/**
 * MemoryRef — a single persisted memory entry.
 * Shape per ADR-0005 §"Key Interfaces":
 *   { id, type, content, metadata, created_at }
 *
 * Optional `ttl` (seconds) — when set, MockMemoryStore evicts the ref after
 * TTL elapses (mirrors KV's expirationTtl behaviour for unit testing).
 */
export interface MemoryRef {
  /** Auto-generated by the store on save. */
  id?: string;
  /** Categorizes the memory entry (conversation / agent_trace / ...). */
  type: MemoryRefType;
  /** Free-form payload (message body, JSON-serialized profile, etc.). */
  content: string;
  /** Side metadata (session_id, user_id, intent, cost_usd, trace_id, ...). */
  metadata?: Record<string, unknown>;
  /** ISO 8601, set by the store on save. */
  created_at?: string;
  /** Optional TTL in seconds (KV semantics). Mock honours it via fake timers. */
  ttl?: number;
}

/**
 * Query filter for MemoryStore.query().
 * All fields optional; multiple fields are AND-ed.
 */
export interface MemoryQueryFilter {
  type?: MemoryRefType;
  /** Substring match against `content`. */
  contentContains?: string;
  /** Equality match against a metadata key. */
  metadata?: Record<string, unknown>;
}

/**
 * MemoryStore — persistence abstraction for the Memory Layer.
 *
 * MockMemoryStore: in-memory Map (Phase 1 default, zero external HTTP).
 * D1MemoryStore: wraps a Cloudflare D1 binding (`env.DB`).
 *
 * KV TTL is exposed via `MemoryRef.ttl` (honoured by both Mock and D1 stores
 * for unit-testable eviction semantics).
 */
export interface MemoryStore {
  /** Persist a ref. Returns the ref with `id` and `created_at` set. */
  save(ref: MemoryRef): Promise<MemoryRef>;
  /** Fetch a ref by id, or null if missing / expired. */
  retrieve(id: string): Promise<MemoryRef | null>;
  /** Return refs matching the filter (no order guarantee). */
  query(filter: MemoryQueryFilter): Promise<MemoryRef[]>;
  /** Delete a ref by id. Returns true if something was deleted. */
  delete(id: string): Promise<boolean>;
}
