import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // OpenNext build output (generated artifacts, not lintable)
    ".open-next/**",
    // Coverage report artifacts (generated by vitest, not lintable)
    "coverage/**",
  ]),
  {
    rules: {
      // Allow _-prefixed unused vars (intentional API stubs, mock params).
      // Convention: prefix with _ to signal "intentionally unused".
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    // Test files: relax `any` restriction for mocks/stubs/D1 bindings.
    // Production code in src/lib/** retains the strict no-explicit-any rule.
    files: ["tests/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
]);

export default eslintConfig;
